version "4.10"

#include "zscript/player.zs"
#include "zscript/hud.zs"
#include "zscript/weapon.zs"
#include "zscript/dampedspring.zs"
#include "zscript/damage.zs"
#include "zscript/armor.zs"
#include "zscript/weapons/testguns.zs"
#include "zscript/weapons/plasmapistol.zs"
#include "zscript/weapons/ump45.zs"
#include "zscript/weapons/shotgun.zs"
#include "zscript/weapons/saw.zs"
#include "zscript/weapons/prifle.zs"
#include "zscript/weapons/rocket.zs"